In [1]:
import numpy as np
import matplotlib.pyplot as plt
import torch

1. What is view() in pytorch?

In [2]:
x = torch.randn(4,4)
x.size()

torch.Size([4, 4])

In [3]:
y = x.view(16)
y.size()

torch.Size([16])

In [4]:
x

tensor([[ 1.2035,  2.3698,  0.8248,  0.6424],
        [-2.2392,  0.8632,  0.4338,  0.2815],
        [-0.1311,  1.3641,  0.8794, -0.1044],
        [ 0.9312,  2.0349, -0.9107,  0.8244]])

In [5]:
y

tensor([ 1.2035,  2.3698,  0.8248,  0.6424, -2.2392,  0.8632,  0.4338,  0.2815,
        -0.1311,  1.3641,  0.8794, -0.1044,  0.9312,  2.0349, -0.9107,  0.8244])

In [6]:
z = x.view(-1, 8)
z.size()

torch.Size([2, 8])

In [7]:
z

tensor([[ 1.2035,  2.3698,  0.8248,  0.6424, -2.2392,  0.8632,  0.4338,  0.2815],
        [-0.1311,  1.3641,  0.8794, -0.1044,  0.9312,  2.0349, -0.9107,  0.8244]])

In [8]:
a = torch.randn(1,2,3,4)
a.size()

torch.Size([1, 2, 3, 4])

In [11]:
print(a)

tensor([[[[-0.6047, -0.0378,  0.4029,  0.2662],
          [-0.8798, -0.1902,  1.1099,  1.1792],
          [-1.2941, -1.5974, -0.8164,  1.8196]],

         [[-1.2594,  0.2700,  1.4183,  0.1470],
          [-1.6542, -0.0181, -0.5845, -0.0466],
          [ 1.7039, -1.6365, -0.0464, -0.3664]]]])


In [9]:
b = a.transpose(1,2)
b.size()

torch.Size([1, 3, 2, 4])

In [12]:
b

tensor([[[[-0.6047, -0.0378,  0.4029,  0.2662],
          [-1.2594,  0.2700,  1.4183,  0.1470]],

         [[-0.8798, -0.1902,  1.1099,  1.1792],
          [-1.6542, -0.0181, -0.5845, -0.0466]],

         [[-1.2941, -1.5974, -0.8164,  1.8196],
          [ 1.7039, -1.6365, -0.0464, -0.3664]]]])

In [13]:
c = a.view(1,3,2,4)
c.size()

torch.Size([1, 3, 2, 4])

In [14]:
torch.equal(b,c)

False

In [15]:
x

tensor([[ 1.2035,  2.3698,  0.8248,  0.6424],
        [-2.2392,  0.8632,  0.4338,  0.2815],
        [-0.1311,  1.3641,  0.8794, -0.1044],
        [ 0.9312,  2.0349, -0.9107,  0.8244]])

In [16]:
x.dtype

torch.float32

In [17]:
y = x.view(torch.int32)
y

tensor([[ 1067060486,  1075292852,  1062414101,  1059353277],
        [-1072738385,  1063057722,  1054743822,  1049634603],
        [-1106889054,  1068407192,  1063330342, -1110060420],
        [ 1064198837,  1073888368, -1083628452,  1062406619]],
       dtype=torch.int32)

2. How vsplit() and hsplit() works?

In [18]:
t = torch.arange(16.0).reshape(4, 4)
t

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [19]:
torch.vsplit(t,2)

(tensor([[0., 1., 2., 3.],
         [4., 5., 6., 7.]]),
 tensor([[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]))

In [20]:
torch.hsplit(t,2)

(tensor([[ 0.,  1.],
         [ 4.,  5.],
         [ 8.,  9.],
         [12., 13.]]),
 tensor([[ 2.,  3.],
         [ 6.,  7.],
         [10., 11.],
         [14., 15.]]))

3. how vstack() works?

In [23]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([4, 5, 6])
print(x)
print(y)

tensor([1, 2, 3])
tensor([4, 5, 6])


In [24]:
torch.vstack((x, y))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
torch.hstack((x, y))

tensor([1, 2, 3, 4, 5, 6])

4. How torch.where() works?

In [26]:
x = torch.randn(4, 5)
y = torch.randn(4, 5)

In [27]:
x

tensor([[-1.9363, -0.2375, -0.4262, -0.1633,  0.0424],
        [-0.5713, -0.4876, -1.4783, -0.5919,  0.7533],
        [-1.7189, -0.3048, -1.8523, -0.7644,  0.3103],
        [-0.9934, -0.6033, -0.4531, -1.1274,  1.8988]])

In [28]:
torch.where(x > 0, x, y)

tensor([[ 1.0236,  0.4721, -0.3302, -0.0831,  0.0424],
        [ 0.7872,  1.7005,  0.3737, -0.7262,  0.7533],
        [ 0.4651,  0.0666,  1.2115,  0.1871,  0.3103],
        [ 0.9689, -1.8796, -0.8368, -0.9153,  1.8988]])

In [29]:
x = torch.randn(2,2, dtype=torch.double)
x

tensor([[ 1.4697, -0.6246],
        [-0.4019, -0.7760]], dtype=torch.float64)

In [30]:
torch.where(x >0, x, 0.)

tensor([[1.4697, 0.0000],
        [0.0000, 0.0000]], dtype=torch.float64)